### ISSUE TITLE
Documentation Project Content Meta-Tracker

### ISSUE THREAD

**Issue by marty-johnson59** [KhronosGroup/Vulkan-Site#62]
Moved over from Antora repo (see comments on issue#2) - from Marty: 

This issue is intended track content development tasks for the Vulkan Documentation Project, with many sub-issues to be resolve (and more to be identified).

* [ ] Vulkan Tutorial
  * [ ] Add Android support [github issue](https://github.com/KhronosGroup/Vulkan-Tutorial/issues/29)
  * [ ] Add MoltenVK support (MacOS and IOS) [github issue](https://github.com/KhronosGroup/Vulkan-Tutorial/issues/20)
  * [ ] Improve HLSL support [github issue](https://github.com/KhronosGroup/Vulkan-Tutorial/issues/18)
  * [x] Convert to asciidoc [github pull request](https://github.com/KhronosGroup/VulkanTutorial/pull/5)
  * [x] Add Antora project setup [github pull request](https://github.com/KhronosGroup/VulkanTutorial/pull/5)
* [ ] Vulkan Guide
  * [ ] Add chapter on render passes, sub-passes [github issue](https://github.com/KhronosGroup/Vulkan-Guide/issues/17)
  * [ ] Add chapter on shader_object?
  * [ ] Add chapter on Profiles [github issue](https://github.com/KhronosGroup/Vulkan-Guide/issues/215)
  * [ ] Add chapter on Roadmaps
  * [ ] Add chapter on "How to Vulkan with latest innovations" [github issue](https://github.com/KhronosGroup/Vulkan-Guide/issues/183)
  * [ ] Fill EXT/KHR gaps
  * [ ] Consistent coverage of EXTs/KHRs (policy needed?)
  * [ ] Add chapter on HLSL <-> GLSL mapping ([github issue](https://github.com/KhronosGroup/Vulkan-Guide/issues/218))
* [ ] Vulkan Sample docs/tutorials ([github issue](https://github.com/KhronosGroup/Vulkan-Samples/issues/729))
  * [x] Convert docs/tutorials from markdown to asciidoc ([github pull request](https://github.com/KhronosGroup/Vulkan-Samples/pull/765))
  * [ ] Add tutorials to README files where missing [github issue](https://github.com/KhronosGroup/Vulkan-Samples/issues/729)
    * [ ] API samples:
      * [ ] Compute shader N-Body simulation
      * [ ] Dynamic Uniform buffers
      * [ ] HDR
      * [ ] Hello Triangle
      * [ ] Instancing
      * [ ] Terrain Tessellation
      * [ ] Texture loading
    * [ ] Extension samples:
      * [ ] Conservative Rasterization
      * [ ] Fragment shading rate
      * [ ] Mesh shading
      * [ ] OpenGL interoperability
      * [ ] Push Descriptors
      * [ ] Basic hardware accelerated ray tracing
      * [ ] Basic ray queries
      * [ ] Synchronizaton2
    * [ ] Performance samples:
      * [ ] Texture compression comparison
* [ ] LunarG docs? TBD. Consider including
  * [ ] [Getting_started](https://vulkan.lunarg.com/doc/sdk/1.3.250.1/windows/getting_started.html)
  * [ ] [Profiles](https://vulkan.lunarg.com/doc/sdk/1.3.250.1/windows/getting_started.html) ([github issue](https://github.com/KhronosGroup/Vulkan-Guide/issues/215))
* [ ] Understanding Vulkan

**Comment by oddhack** [comment]
@marty-johnson59 is this still useful? All this stuff seems to get touched on periodically in the docs / samples calls anyway and this is probably way out of date. Suggest closing.

**Comment by marty-johnson59** [comment]
Yep, I think we're done with this one...closing
